return {
  -- {
  --   'yetone/avante.nvim',
  --   event = 'VeryLazy',
  --   version = false, -- set this if you want to always pull the latest change
  --   opts = {
  --     provider = 'claude',
  --     auto_suggestions = true,
  --     behaviour = {
  --       auto_suggestions = true,
  --       auto_set_highlight_group = true,
  --       auto_set_keymaps = true,
  --       auto_apply_diff_after_generation = false,
  --       auto_focus_sidebar = true,
  --       jump_to_result_buffer_on_finish = false,
  --       minimize_diff = true,
  --       support_paste_from_clipboard = true,
  --       enable_token_counting = true,
  --     },
  --     mappings = {
  --       -- Inline suggestions
  --       suggestion = {
  --         accept = '<C-a>',
  --         next = '<C-n>',
  --         prev = '<C-p>',
  --         dismiss = '<C-c>',
  --       },
  --       -- Diff operations (used in diff view)
  --       diff = {
  --         ours = '<leader>do',
  --         theirs = '<leader>dt',
  --         all_theirs = '<leader>da',
  --         both = '<leader>db',
  --         cursor = '<leader>dc',
  --         next = '<leader>dn',
  --         prev = '<leader>dp',
  --       },
  --       -- Jump navigation (sidebar)
  --       jump = {
  --         next = '<leader>aj',
  --         prev = '<leader>ak',
  --       },
  --       -- Submit/Cancel (chat interactions)
  --       submit = {
  --         normal = '<CR>',
  --         insert = '<C-s>',
  --       },
  --       cancel = {
  --         normal = { '<C-x>', '<Esc>', 'q' },
  --         insert = { '<C-x>' },
  --       },
  --     },
  --     windows = {
  --       position = 'right',
  --       wrap = true,
  --       width = 30,
  --       height = 30,
  --       sidebar_header = {
  --         enabled = true,
  --         align = 'center',
  --         rounded = true,
  --       },
  --       fillchars = {
  --         eob = ' ',
  --       },
  --     },
  --     providers = {
  --       claude = {
  --         endpoint = 'https://api.anthropic.com',
  --         model = 'claude-sonnet-4-20250514',
  --         timeout = 30000,
  --         extra_request_body = {
  --           temperature = 0.75,
  --           max_tokens = 4096,
  --         },
  --       },
  --     },
  --   },
  --   -- if you want to build from source then do `make BUILD_FROM_SOURCE=true`
  --   build = 'make',
  --   -- build = "powershell -ExecutionPolicy Bypass -File Build.ps1 -BuildFromSource false" -- for windows
  --   dependencies = {
  --     'nvim-treesitter/nvim-treesitter',
  --     'stevearc/dressing.nvim',
  --     'nvim-lua/plenary.nvim',
  --     'MunifTanjim/nui.nvim',
  --     --- The below dependencies are optional,
  --     'nvim-tree/nvim-web-devicons', -- or echasnovski/mini.icons
  --     'nvim-telescope/telescope.nvim', -- for file_selector provider telescope
  --     'hrsh7th/nvim-cmp',
  --     -- 'zbirenbaum/copilot.lua', -- for providers='copilot' (disabled)
  --     {
  --       -- Compatibility layer for blink.cmp integration
  --       'saghen/blink.compat',
  --       version = '2.*',
  --       lazy = true,
  --       opts = {},
  --     },
  --     {
  --       -- support for image pasting
  --       'HakonHarnes/img-clip.nvim',
  --       event = 'VeryLazy',
  --       opts = {
  --         -- recommended settings
  --         default = {
  --           embed_image_as_base64 = false,
  --           prompt_for_file_name = false,
  --           drag_and_drop = {
  --             insert_mode = true,
  --           },
  --           -- required for Windows users
  --           use_absolute_path = true,
  --         },
  --       },
  --     },
  --     {
  --       -- Make sure to set this up properly if you have lazy=true
  --       'MeanderingProgrammer/render-markdown.nvim',
  --       opts = {
  --         file_types = { 'markdown', 'Avante' },
  --       },
  --       ft = { 'markdown', 'Avante' },
  --     },
  --   },
  -- },
}
