import = [
    "~/.config/alacritty/themes/themes/monokai_charcoal.toml"
]
[font.normal]
family = "MesloLGS Nerd Font"

[font.bold]
family = "MesloLGS Nerd Font"

[font.italic]
family = "MesloLGS Nerd Font"

[font.bold_italic]
family = "MesloLGS Nerd Font"

[font]
size = 11.8
