# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# Run Sketchybar together with AeroSpace
# sketchbar has a built-in detection of already running process,
# so it won't be run twice on AeroSpace restart
after-startup-command = ['exec-and-forget sketchybar']

# Notify Sketchybar about workspace change
exec-on-workspace-change = [
    '/bin/bash',
    '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE',
]

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# The 'accordion-padding' specifies the size of accordion padding
accordion-padding = 10

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']


[workspace-to-monitor-force-assignment]
1 = 1
2 = 1
3 = 1
4 = [2, 1]
5 = [2, 1]
6 = [2, 1]
7 = [3, 2, 1]
8 = [3, 2, 1]
9 = [3, 2, 1]


# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 2
inner.vertical = 2
outer.left = 0
outer.bottom = 0
outer.top = [{ monitor."retina" = 0 }, { monitor."*" = 27 }]
outer.right = 0


[mode.main.binding]

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right


# VIEWS
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'


alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'

alt-h = 'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors left'
alt-j = 'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors down'
alt-k = 'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors up'
alt-l = 'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors right'

alt-n = 'focus right'
alt-p = 'focus left'

shift-alt-ctrl-n = 'focus-monitor --wrap-around next'
shift-alt-ctrl-p = 'focus-monitor --wrap-around prev'

alt-shift-n = 'workspace --wrap-around next'
alt-shift-p = 'workspace --wrap-around prev'

# MODIFY/MOVE WINDOWS

alt-backslash = 'resize smart -50'
alt-backtick = 'resize smart +50'

alt-shift-cmd-ctrl-h = 'move left'
alt-shift-cmd-ctrl-j = 'move down'
alt-shift-cmd-ctrl-k = 'move up'
alt-shift-cmd-ctrl-l = 'move right'

alt-shift-ctrl-cmd-f = 'layout floating tiling' # Toggle between floating and tiling layout
alt-shift-ctrl-cmd-m = 'fullscreen'             # Toggle between floating and tiling layout

alt-shift-ctrl-cmd-1 = 'move-node-to-workspace 1'
alt-shift-ctrl-cmd-2 = 'move-node-to-workspace 2'
alt-shift-ctrl-cmd-3 = 'move-node-to-workspace 3'
alt-shift-ctrl-cmd-4 = 'move-node-to-workspace 4'
alt-shift-ctrl-cmd-5 = 'move-node-to-workspace 5'
alt-shift-ctrl-cmd-6 = 'move-node-to-workspace 6'
alt-shift-ctrl-cmd-7 = 'move-node-to-workspace 7'
alt-shift-ctrl-cmd-8 = 'move-node-to-workspace 8'
alt-shift-ctrl-cmd-9 = 'move-node-to-workspace 9'

alt-shift-ctrl-cmd-n = [
    'move-node-to-workspace --wrap-around next',
    'workspace --wrap-around next',
]
alt-shift-ctrl-cmd-p = [
    'move-node-to-workspace --wrap-around prev',
    'workspace --wrap-around prev',
]


alt-shift-ctrl-cmd-q = ['move-node-to-monitor 1', 'focus-monitor 1']
alt-shift-ctrl-cmd-w = ['move-node-to-monitor 2', 'focus-monitor 2']
alt-shift-ctrl-cmd-e = ['move-node-to-monitor 3', 'focus-monitor 3']


alt-shift-semicolon = 'mode service'
[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
#s = ['layout sticky tiling', 'mode main'] # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
backspace = ['close-all-windows-but-current', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']


#CALLBACKS
[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = 'layout floating'
