[Normal_Mode]
"ctrl-shift-H" = 'Move to the left pane'
"ctrl-shift-L" = 'Move to the right pane'
"ctrl-shift-J" = 'Move to the bottom pane'
"ctrl-shift-K" = 'Move to the top pane'
"ctrl-alt-shift-H" = 'resize pane to the left'
"ctrl-alt-shift-L" = 'resize pane to the right'
"ctrl-alt-shift-J" = 'resize pane to the bottom'
"ctrl-alt-shift-K" = 'resize pane to the top'
"ctrl-Tab" = 'Next tab'
"ctrl-shift-Tab" = 'Previous tab'
"ctrl-shift-Enter" = 'Toggle fullscreen'
"ctrl-shift-_" = 'Split vertically'
"ctrl-shift-/" = 'Split horizontally'
"ctrl-shift-C" = 'Close pane'
"ctrl-shift-D" = 'Show debug overlay'
"ctrl-shift-P" = 'Activate command palette'
"ctrl-shift-R" = 'Reload configuration'
"ctrl-shift-W" = 'Close tab'
"ctrl-shift-X" = 'Activate copy mode'
"ctrl-shift-Z" = 'Zoom in on current split pane'
"cmd-_" = 'Decrease font size'
"cmd-Enter" = 'Increase font size'
"cmd-C" = 'Copy to clipboard'
"cmd-F" = 'Search'
"cmd-K" = 'Clear scrollback'
"cmd-M" = 'Hide'
"cmd-N" = 'Spawn window'
"cmd-Q" = 'Quit application'
"cmd-R" = 'Reload configuration'
"cmd-T" = 'Spawn tab'
"cmd-V" = 'Paste from clipboard'
"cmd-W" = 'Close tab'

