#!/usr/bin/env sh


yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa


yabai -m config window_gap 2

yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"

# yabai -m config window_opacity on
# yabai -m config active_window_opacity 1.0
# yabai -m config normal_window_opacity 0.95

# set mouse follows focus mode (default: off)
# When yabai focuses another window, the mouse cursor gets moved to the center of the focused window
yabai -m config mouse_follows_focus on

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(1Password|AWS VPN Client|Postico|Docker Desktop|LuLu|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off

yabai -m config external_bar all:32:0


echo "yabai configuration loaded.."
